config/routes.rb
Rails.application.routes.draw do
  root to: 'timelines#index'
  devise_for :users
  resources :timelines do
    collection do
      post 'filter_by_user'
    end
  resources :likes, only: [:create, :destroy]
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  

end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :timeline
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
    belongs_to :user
    has_many :likes
    has_many :replies, class_name: 'Timeline', foreign_key: 'reply_id', dependent: :destroy
    validates :message, presence: true, allow_blank: false, length: { maximum: 140 }
    scope :user_filter, -> user_id do
    # user_idパラメータがあればフィルターをかける
    where(user_id: user_id) if user_id.present?
  end
  
  scope :not_reply, ->  do
    # 返信でないデータを取得
    where(reply_id: nil)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :likes
  has_many :timelines
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :thumbnail, UserThumbnailUploader
  validates :name, presence: true
  validates :agreement, presence: true, acceptance: {accept: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :thumbnail, :agreement])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = Like.new(user_id: current_user.id, timeline_id: params[:timeline_id])
        like.save
        redirect_to timelines_path
    end
    
    def destory
        like = Like.find_by(user_id: current_user.id, timeline_id: params[:timeline_id])
        like.destroy
        redirect_to timelines_path
    end
    
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    # メッセージ入力
    @input_message = params[:id] ? Timeline.find(params[:id]) : Timeline.new
    # タイムラインを取得
    @timeline = Timeline.includes(:user).not_reply.user_filter(params[:filter_user_id]).order('updated_at DESC')
    @users = User.all
    if params[:reply_id]
      # 返信時は返信のタイムライン情報を取得
      @reply_timeline = Timeline.find(params[:reply_id])
    end
  end
  
  def create
    timeline = Timeline.new
    timeline.attributes = input_message_param
    timeline.user_id = current_user.id
    if timeline.valid? # バリデーションチェック
      timeline.save!        
      respond_to do |format|
         format.html do
           # indexへリダイレクトさせる処理
           redirect_to action: :index
         end
         format.json do
           html = render_to_string partial: 'timelines/timeline', layout: false, formats: :html, locals: { t: timeline }
           render json: { timeline: html }
         end
       end
    else
      respond_to do |format|
         format.html do
           flash[:alert] = timeline.errors.full_messages
           redirect_to action: :index
         end
         format.json do
           render json: { error: timeline.errors.full_messages }
         end
       end
    end
  end
  
  def update
    timeline = Timeline.find(params[:id])
    timeline.attributes = input_message_param
    if timeline.valid? # バリデーションチェック
      timeline.save!
    else
      flash[:alert] = timeline.errors.full_messages
    end
    redirect_to action: :index
  end
  
  def destroy
    timeline = Timeline.find(params[:id])
    timeline.destroy
    redirect_to action: :index
  end
  
  def filter_by_user
    if params[:filter_user_id].present?
      redirect_to action: :index, filter_user_id: params[:filter_user_id]
    else
      # フィルターなし
      redirect_to action: :index
    end
  end

  private
  def input_message_param
    params.require(:timeline).permit(:message, :reply_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
    # 自分の投稿か判定する
  def mypost?(timeline)
    timeline.user.id == current_user.id
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElitesMessenger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <div class="logout_wrapper">
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  </div>
<% end %>

<p class="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/likes/_likes.html.erb
<% if user_signed_in? %>
  <% if timeline.like_user(current_user.id) %>
    <%= button_to timeline_like_path(like, timeline_id: timeline.id), method: :delete, id: "like-button", remote: true do %>
      <%= image_tag("icon_red_heart.svg") %>
      <span>
        <%= timeline.like_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to timeline_likes_path(timeline), id: "like-button", remote: true do %>
      <%= image_tag("icon_heart.svg") %>
      <span>
        <%= timeline.like_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <% = image_tag("icon_heart.svg") %>
    <span>
      <%= timeline.like_count %>
    </span>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { tweets: @tweets, likes: @likes, like: @like}) %>")

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { tweets: @tweets, likes: @likes }) %>");

app/views/timelines/_timeline.html.erb
<%
  # is_replyの変数を設定
  is_reply = false if is_reply.nil?
%>

<div class="per <%= 'mine' if mypost?(t) %> <%= 'reply' if is_reply %>">
  <p class="icon">
    <!-- サムネイルの設定確認 -->
    <% if t.user.thumbnail? %>
      <%= image_tag t.user.thumbnail.url %>
    <% else %>
      NO IMAGE
    <% end %>
  </p>
  <%= simple_format t.message, class: 'message' %>
  <% if mypost?(t) %>
    <div class="operation">
    <!-- 自分の投稿の場合、編集ボタンを表示 -->
      <%= link_to root_path(id: t.id, message: t.message) do %>
      <%= button_tag 'Edit', class: 'btn btn-info' %>
      <% end %>
      <%= button_to 'Del', timeline_path(t), method: :delete, class: 'btn btn-danger', data: {confirm: '削除してよろしいですか？'}  %>
    </div>
  <% else %>
    <div class="operation">
    <!-- 他人の投稿の場合、Reボタンを表示 -->
      <%= link_to root_path(reply_id: t.id) do %>
      <%= button_tag 'Re', class: 'btn btn-info' %>
  <% end %>
    
    <%= button_to 'like', timeline_likes_path(t.id), method: :post, class: 'btn btn-danger' if t.likes.where(user_id: current_user.id).count == 0 %>
  </div>
    <% end %>   
    <% if t.likes.count > 0 %>
    いいね!<%= t.likes.count %>件
    <% end %>
</div>
<% t.replies.each do |r| %>
  <%= render 'timelines/timeline', t: r, is_reply: true %>
<% end %>

app/views/timelines/index.html.erb
<div class="wrapper timeline_wrapper">

  <div class="input">
    <%= form_for @input_message, remote: true, html: {class: 'input_message_form'}, format: :json, authenticity_token: true do |f| %>
      <div class="form-group">
        <%= f.label :message %><br/>
        <!--** 編集中の場合は場合はメッセージを表示 **-->
        <% if @input_message.persisted? %>
          編集中
        <% elsif @reply_timeline %>
          <%= @reply_timeline.user.name %>の「<%= truncate(@reply_timeline.message, length: 7) %>」に返信  
        <% end %>
        <br/>
        <%= f.text_area :message, class: 'form-control', rows: 3 %>
      </div>
      <div class="actions clearfix">
        <div class="alert">
          <% if flash[:alert] %>
            <% flash[:alert].each do |message| %>
              <p class="alert"><%= message %></p>
            <% end %>
          <% end %>
        </div>
        
        <div class="post">
          <!--** 編集中は編集をキャンセルするボタンを表示 **-->
          <% if @input_message.persisted? || @reply_timeline %>
            <%= link_to root_path do %>
              <%= button_tag 'Cancel', class: 'btn btn-default' %>
            <% end %>
          <% end %>
          <%= f.submit 'Post', class: 'btn btn-primary post' %>
          <%= f.submit 'AjaxPost', class: 'btn btn-primary ajaxpost' %>
        </div>
      </div>
      <%= f.hidden_field :reply_id, value: @reply_timeline.id if @reply_timeline %>
    <% end %>
  </div>
  <div class="user_filter">
    <%= form_tag filter_by_user_timelines_path do |f| %>
      <div class="form-group">
        <label>ユーザフィルター</label><br/>
        <%= select_tag :filter_user_id, options_for_select(@users.map { |m| [m.name, m.id] }, params[:filter_user_id]), prompt: 'フィルターなし', class: 'form-control' %>
      </div>
      <div class="actions">
        <%= submit_tag 'Apply', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  <!-- タイムライン -->
  <div class="timeline">
    <% @timeline.each do |t| %>
    <%= render 'timelines/timeline', t: t %>
    <% end %>
  </div>
</div>